import React from "react";
import { useLocalSearchParams } from "expo-router";
import { ScreenLayout } from "@components/screen-layout/screen-layout";
import { Header } from "@components/navigation/headers/header";
import { gql, useQuery } from "@apollo/client";
import {
  GetArticleBySlugQuery,
  GetArticleBySlugQueryVariables,
} from "@/gql/graphql";
import ParseHtml from "@components/article/parse-html";
import { useScreenType } from "@hooks/useScreenType";
import TopBar from "@components/navigation/top-bar/top-bar";
import { View } from "react-native";
import CustomNotFound from "@/app/+not-found";
import { apolloIsNotFoundError } from "@/utils/apollo-errors";
import RebuildrHead from "@components/meta-data/rebuildr-head";
import { fetchAllArticles } from "@/lib/seo-fetch";
import articlesSeo from "@/lib/articles-seo.generated.json";
import { LoadingSpinner } from "@components/loading-spinner/loading-spinner";
import { articleSchema } from "@/lib/structured-data";

const GET_ARTICLE_BY_SLUG = gql`
  query GetArticleBySlug($slug: String!) {
    articleBySlug(slug: $slug) {
      id
      title
      body
    }
  }
`;

/**
 * Enumerates every article so `expo export -p web` prerenders one static HTML
 * file per /article/<slug> instead of falling back to the empty SPA shell.
 * Resilient: if the API is unreachable at build time we return [] (articles then
 * render client-side, same as before) rather than failing the whole build.
 */
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  try {
    const articles = await fetchAllArticles();
    return articles.map((a) => ({ slug: a.slug }));
  } catch (err) {
    console.warn(
      "generateStaticParams(article): API unreachable, skipping:",
      err,
    );
    return [];
  }
}

// Build-time per-article SEO map (regenerated by scripts/generate-sitemap.ts).
// Lets the static HTML carry a real per-article title, short meta description,
// the FULL body and publish dates — all server-rendered, no client-side fetch.
const seoData = articlesSeo as Record<
  string,
  {
    title: string;
    description: string;
    body: string;
    isInternal?: boolean;
    datePublished?: string;
    dateModified?: string;
  }
>;

export default function ArticlePage() {
  const { isDesktop } = useScreenType();
  const { slug } = useLocalSearchParams<{ slug: string }>();

  const { data, error } = useQuery<
    GetArticleBySlugQuery,
    GetArticleBySlugQueryVariables
  >(GET_ARTICLE_BY_SLUG, {
    variables: { slug },
  });

  if (error && apolloIsNotFoundError(error)) {
    return <CustomNotFound />;
  }

  const seoEntry = seoData[slug];
  // Title/body/dates: live data when loaded (client), otherwise the build-time
  // map so the static HTML has the real, per-article title + FULL body + dates.
  const title = data?.articleBySlug.title ?? seoEntry?.title;
  const body = data?.articleBySlug.body ?? seoEntry?.body;

  // NB: RebuildrHead is rendered as a sibling of ScreenLayout, not a child.
  // ScreenLayout swallows its children while loading, which would otherwise drop
  // the metadata from the static HTML.
  const description =
    seoEntry?.description ||
    `${title} – guide om återbruk och återbrukat byggmaterial från RebuildR.`;
  const head = title ? (
    <RebuildrHead
      title={title}
      description={description}
      ogType="article"
      noindex={!!seoEntry?.isInternal}
      jsonLd={articleSchema({
        title,
        description,
        slug,
        datePublished: seoEntry?.datePublished,
        dateModified: seoEntry?.dateModified,
      })}
    />
  ) : null;

  // Full parsed body is server-rendered (real content for non-JS crawlers/AI),
  // since `body` falls back to the build-time map before Apollo resolves. Client
  // first render matches the server (same build-time body) → no hydration
  // mismatch; Apollo's live body swaps in once loaded.
  const articleContent = body ? <ParseHtml html={body} /> : <LoadingSpinner />;

  if (isDesktop) {
    return (
      <>
        {head}
        <ScreenLayout headerComponent={<TopBar theme="light" />}>
          <View style={{ width: 720, alignSelf: "center", gap: 24 }}>
            <Header showBackButton title={title} headingLevel={1} />
            {articleContent}
          </View>
        </ScreenLayout>
      </>
    );
  }

  return (
    <>
      {head}
      <ScreenLayout
        headerComponent={
          <Header showBackButton title={title} headingLevel={1} />
        }
      >
        {articleContent}
      </ScreenLayout>
    </>
  );
}
