import React from "react";
import { useLocalSearchParams } from "expo-router";
import { ScreenLayout } from "@components/screen-layout/screen-layout";
import { Header } from "@components/navigation/headers/header";
import { gql, useQuery } from "@apollo/client";
import {
  GetArticleBySlugQuery,
  GetArticleBySlugQueryVariables,
} from "@/gql/graphql";
import ParseHtml from "@components/article/parse-html";
import { useScreenType } from "@hooks/useScreenType";
import TopBar from "@components/navigation/top-bar/top-bar";
import { View } from "react-native";
import CustomNotFound from "@/app/+not-found";
import { apolloIsNotFoundError } from "@/utils/apollo-errors";
import RebuildrHead from "@components/meta-data/rebuildr-head";
import { fetchAllArticles } from "@/lib/seo-fetch";
import articlesSeo from "@/lib/articles-seo.generated.json";
import { Body } from "@components/typography/text";
import { LoadingSpinner } from "@components/loading-spinner/loading-spinner";
import { articleSchema } from "@/lib/structured-data";

const GET_ARTICLE_BY_SLUG = gql`
  query GetArticleBySlug($slug: String!) {
    articleBySlug(slug: $slug) {
      id
      title
      body
    }
  }
`;

/**
 * Enumerates every article so `expo export -p web` prerenders one static HTML
 * file per /article/<slug> instead of falling back to the empty SPA shell.
 * Resilient: if the API is unreachable at build time we return [] (articles then
 * render client-side, same as before) rather than failing the whole build.
 */
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  try {
    const articles = await fetchAllArticles();
    return articles.map((a) => ({ slug: a.slug }));
  } catch (err) {
    console.warn(
      "generateStaticParams(article): API unreachable, skipping:",
      err,
    );
    return [];
  }
}

// Build-time slug -> {title, excerpt} map (regenerated by scripts/generate-sitemap.ts).
// Lets the static HTML carry a real per-article title, meta description and a
// text excerpt without a client-side fetch.
const seoData = articlesSeo as Record<
  string,
  { title: string; excerpt: string }
>;

export default function ArticlePage() {
  const { isDesktop } = useScreenType();
  const { slug } = useLocalSearchParams<{ slug: string }>();

  const { data, error } = useQuery<
    GetArticleBySlugQuery,
    GetArticleBySlugQueryVariables
  >(GET_ARTICLE_BY_SLUG, {
    variables: { slug },
  });

  if (error && apolloIsNotFoundError(error)) {
    return <CustomNotFound />;
  }

  const seoEntry = seoData[slug];
  // Title for <title>/<h1>: live data when loaded (client), otherwise the
  // build-time map so the static HTML has a real, per-article title.
  const title = data?.articleBySlug.title ?? seoEntry?.title;
  const excerpt = seoEntry?.excerpt;
  const body = data?.articleBySlug.body;

  // NB: RebuildrHead is rendered as a sibling of ScreenLayout, not a child.
  // ScreenLayout swallows its children while loading, which would otherwise drop
  // the metadata from the static HTML.
  const description =
    excerpt ||
    `${title} – guide om återbruk och återbrukat byggmaterial från RebuildR.`;
  const head = title ? (
    <RebuildrHead
      title={title}
      description={description}
      jsonLd={articleSchema({ title, description, slug })}
    />
  ) : null;

  // Progressive content: full parsed body once loaded; before that the
  // server-rendered excerpt (real text for non-JS crawlers, content preview for
  // users); spinner only when we have neither. We pass loading={false} to
  // ScreenLayout and manage these states here so the excerpt reaches the static
  // HTML. Client first render matches the server (no data yet) → no hydration
  // mismatch.
  const articleContent = body ? (
    <ParseHtml html={body} />
  ) : excerpt ? (
    <Body size="large">{excerpt}</Body>
  ) : (
    <LoadingSpinner />
  );

  if (isDesktop) {
    return (
      <>
        {head}
        <ScreenLayout headerComponent={<TopBar theme="light" />}>
          <View style={{ width: 720, alignSelf: "center", gap: 24 }}>
            <Header showBackButton title={title} headingLevel={1} />
            {articleContent}
          </View>
        </ScreenLayout>
      </>
    );
  }

  return (
    <>
      {head}
      <ScreenLayout
        headerComponent={
          <Header showBackButton title={title} headingLevel={1} />
        }
      >
        {articleContent}
      </ScreenLayout>
    </>
  );
}
