// WebP size variants generated by the backend ImageVariantService
// (see rebuildr-backend/src/services/image-variant.service.ts). Stored next to
// the original in DO Spaces as `{id}_{width}.webp`.
const VARIANT_WIDTHS = [200, 400, 800] as const;

type VariantImage =
  | { url?: string | null; hasVariants?: boolean | null }
  | null
  | undefined;

/**
 * Returns an optimized WebP variant URL for a product image when the backend has
 * generated variants (`image.hasVariants`); otherwise the original `url`.
 *
 * We only use a variant when `hasVariants` is true so we never request a
 * `{id}_{width}.webp` that hasn't been generated yet (which would 404) — the
 * original is served until the cron sweep has processed the image.
 */
export function variantUrl(
  image: VariantImage,
  targetWidth: number,
): string | undefined {
  const url = image?.url ?? undefined;
  if (!url || !image?.hasVariants) return url;

  const width =
    VARIANT_WIDTHS.find((w) => w >= targetWidth) ??
    VARIANT_WIDTHS[VARIANT_WIDTHS.length - 1];

  // Replace the trailing "/{id}.{ext}" with "/{id}_{width}.webp".
  return url.replace(/\/([^/]+)\.[^/.]+$/, `/$1_${width}.webp`);
}
