export type IFetchBusinessResponse = {
  PeOrgNr: string;
  OrgNr: string;
  Företagsnamn: string;
  COAdress: string;
  PostAdress: string;
  PostNr: string;
  PostOrt: string;
  'Säteskommun, kod': string;
  Säteskommun: string;
  'Säteslän, kod': string;
  Säteslän: string;
  'Aregion, kod': string;
  ARegion: string;
  'Antal arbetsställen': string;
  'Stkl, kod': string;
  Storleksklass: string;
  'Företagsstatus, kod': string;
  Företagsstatus: string;
  'Registrerad hos SKV, kod': string;
  'Registrerad hos SKV': string;
  'Juridisk form, kod': string;
  'Juridisk form': string;
  'Reklam, kod': string;
  Reklam: string;
  'Utskick, kod': string;
  Utskick: string;
  Startdatum: string;
  Slutdatum: string;
  Registreringsdatum: string;
  'Bransch_1, kod': string;
  'Bransch_1P, kod': string;
  Bransch_1: string;
  'Avdelning_1, kod': string;
  Avdelning_1: string;
  'Bransch_2, kod': string;
  'Bransch_2P, kod': string;
  Bransch_2: string;
  'Avdelning_2, kod': string;
  Avdelning_2: string;
  'Bransch_3, kod': string;
  'Bransch_3P, kod': string;
  Bransch_3: string;
  'Avdelning_3, kod': string;
  Avdelning_3: string;
  'Bransch_4, kod': string;
  'Bransch_4P, kod': string;
  Bransch_4: string;
  'Avdelning_4, kod': string;
  Avdelning_4: string;
  'Bransch_5, kod': string;
  'Bransch_5P, kod': string;
  Bransch_5: string;
  'Avdelning_5, kod': string;
  Avdelning_5: string;
  'Export/Importmarkering': string;
  'Omsättning, år': string;
  'Stkl, oms, kod': string;
  'Storleksklass, oms': string;
  'Stkl Fin, oms, kod': string;
  'Storleksklass Fin, oms': string;
  'Ägarkategori, kod': string;
  Ägarkategori: string;
  Telefon: string;
  'E-post': string;
  'Privat/Publikt, kod': string;
  'Privat/Publikt': string;
  'Arbetsgivarstatus, kod': string;
  Arbetsgivarstatus: string;
  'Momsstatus, kod': string;
  Momsstatus: string;
  'Fskattstatus, kod': string;
  Fskattstatus: string;
  'Bolagsstatus, kod': string;
  Bolagsstatus: string;
  'Antal firmor': string;
  Firma: string;
  'Sektor, kod': string;
  Sektor: string;
  'Stkl SME, kod': string;
  'Storleksklass SME': string;
  'Andel kvinna': string;
  'Andel man': string;
  'Ägarland, kod': string;
  Ägarland: string;
  Ägarnamn: string;
  'Utländskt ägande, kod': string;
  'Utländskt ägande': string;
  'Stkl export, kod': string;
  'Stkl export': string;
  'Stkl import, kod': string;
  'Stkl import': string;
  Norden: string;
  EU: string;
  'Övriga Europa': string;
  'Asien, ej Fjärran Östern': string;
  'Fjärran Östern': string;
  'Nord- och Centralamerika': string;
  Sydamerika: string;
  Afrika: string;
}[];
