export enum queryKeys {
  GET_PROFILE = "get-profile",
  LIST_IMAGES = "list-images",
  LIST_DOCUMENTS = "list-documents",
  LIST_ARTICLES = "list-articles",
  LIST_USERS = "list-users",
  LIST_FOOTER_SECTIONS = "list-footer-sections",
  LIST_PRODUCTS = "list-products",
  LIST_PROJECTS = "list-projects",
  LIST_CATEGORY = "list-category",
  LIST_ROOT_CATEGORIES = "list-root-categories",
  LIST_PURCHASES = "list-purchases",
  ALL_BRAND = "all-brand",
  LIST_BRAND = "list-brand",
  LIST_PARTNER = "list-partner",
  LIST_SHIPPING_PRICE = "list-shipping-price",
  SEARCH_ADDRESS = "search-address",
  LIST_USER_PROJECTS = "list-user-projects",
  CAN_DELETE_BRAND = "can-delete-brand",
  CATEGORIES_CO2_FACTOR = "categories-co2-factor",
  LIST_CO2_FACTORS = "list-co2-factors",
  LIST_PAGE_CONTENTS = "list-page-contents",
  LIST_BANNERS = "list-banners",
  GET_USER = "get-user",
  NEWSLETTER_COMPETITION = "newsletter-competition",
}
