export enum queryKeys {
  GET_PROFILE = "get-profile",
  LIST_IMAGES = "list-images",
  LIST_ARTICLES = "list-articles",
  LIST_USERS = "list-users",
  LIST_FOOTER_SECTIONS = "list-footer-sections",
  LIST_PRODUCTS = "list-products",
  LIST_PROJECTS = "list-projects",
  LIST_CATEGORY = "list-category",
  LIST_ROOT_CATEGORIES = "list-root-categories",
  ALL_BRAND = "all-brand",
  LIST_BRAND = "list-brand",
  LIST_SHIPPING_PRICE = "list-shipping-price",
  SEARCH_ADDRESS = "search-address",
  LIST_USER_PROJECTS = "list-user-projects",
}
